// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

var options = /* :: */[
  "20",
  /* :: */[
    "40",
    /* :: */[
      "60",
      /* :: */[
        "80",
        /* :: */[
          "100",
          /* :: */[
            "120",
            /* :: */[
              "140",
              /* :: */[
                "151",
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

function Controls(Props) {
  var search = Props.search;
  var count = Props.count;
  var handleSearchChange = Props.handleSearchChange;
  var handleCountChange = Props.handleCountChange;
  return React.createElement("section", {
              className: "controls"
            }, React.createElement("div", {
                  className: "controls__input-container"
                }, React.createElement("label", {
                      className: "controls__input-label",
                      htmlFor: "search"
                    }, React.createElement("strong", undefined, "Search Pokemon")), React.createElement("input", {
                      className: "controls__input",
                      id: "search",
                      type: "text",
                      value: search,
                      onChange: handleSearchChange
                    })), React.createElement("select", {
                  className: "controls__select",
                  value: String(count),
                  onChange: handleCountChange
                }, $$Array.of_list(List.map((function (num) {
                            return React.createElement("option", {
                                        key: num,
                                        value: num
                                      }, num);
                          }), options))));
}

var make = Controls;

exports.options = options;
exports.make = make;
/* react Not a pure module */
