// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var typeToIcon = Js_dict.fromArray(/* array */[
      /* tuple */[
        "Bug",
        "/Bug@2x.png"
      ],
      /* tuple */[
        "Dark",
        "/Dark@2x.png"
      ],
      /* tuple */[
        "Dragon",
        "/Dragon@2x.png"
      ],
      /* tuple */[
        "Electric",
        "/Electric@2x.png"
      ],
      /* tuple */[
        "Fairy",
        "/Fairy@2x.png"
      ],
      /* tuple */[
        "Fighting",
        "/Fight@2x.png"
      ],
      /* tuple */[
        "Fire",
        "/Fire@2x.png"
      ],
      /* tuple */[
        "Ghost",
        "/Ghost@2x.png"
      ],
      /* tuple */[
        "Grass",
        "/Grass@2x.png"
      ],
      /* tuple */[
        "Ground",
        "/Ground@2x.png"
      ],
      /* tuple */[
        "Ice",
        "/Ice@2x.png"
      ],
      /* tuple */[
        "Normal",
        "/Normal@2x.png"
      ],
      /* tuple */[
        "Poison",
        "/Poison@2x.png"
      ],
      /* tuple */[
        "Psychic",
        "/Psychic@2x.png"
      ],
      /* tuple */[
        "Rock",
        "/Rock@2x.png"
      ],
      /* tuple */[
        "Steel",
        "/Steel@2x.png"
      ],
      /* tuple */[
        "Water",
        "/Water@2x.png"
      ]
    ]);

function PokemonEntry(Props) {
  var pokemon = Props.pokemon;
  return React.createElement("div", undefined, React.createElement("img", {
                  className: "pokemon-image",
                  alt: Belt_Option.getWithDefault(pokemon.name, ""),
                  src: Belt_Option.getWithDefault(pokemon.image, "")
                }), React.createElement("h2", undefined, Belt_Option.getWithDefault(pokemon.name, "")), React.createElement("div", {
                  className: "pokemon-types"
                }, $$Array.map((function (t) {
                        var type_ = Belt_Option.getWithDefault(t, "");
                        var match = Js_dict.get(typeToIcon, type_);
                        if (match !== undefined) {
                          return React.createElement("div", {
                                      className: "pokemon-type"
                                    }, React.createElement("img", {
                                          className: "pokemon-type-icon",
                                          alt: type_,
                                          src: match
                                        }), React.createElement("span", {
                                          className: "pokemon-type-text"
                                        }, type_));
                        } else {
                          return null;
                        }
                      }), Belt_Option.getWithDefault(pokemon.types, /* array */[]))));
}

var make = PokemonEntry;

exports.typeToIcon = typeToIcon;
exports.make = make;
/* typeToIcon Not a pure module */
